jobs:
  verify:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Fetch Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./action/main

name: Action

on:
  schedule:
    - cron: "25 1/3 * * *"
